version: '3'
volumes:
  data-volume: {}
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=test_schedule
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - KEY_WEATHER=14e5e7c6
    volumes:
      - .:/src/app
    command: npm run go
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - data-volume:/var/lib/mysql
      - ./db/test_schedule.sql:/docker-entrypoint-initdb.d/init.sql
    command: mysqld --init-file="/docker-entrypoint-initdb.d/init.sql"
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_schedule
      MYSQL_USER: root
      MYSQL_PASSWORD: root
